### ISSUE TITLE
Collapse button on the tray itself, possibly near the name.

### ISSUE THREAD

**Issue by Orionox** [teroparvinen/foundry-action-pack#29]
would be nice to have a collapse button on the tray itself, I'm running into an issue where the tray is just perpetually out, even when set to "token selected"". I can deselect any unit, and the tray just defaults to open on my default character for my players. I can never remember the right hotkey and I don't like cluttering up the token controls anymore than they already are. So it would be nice if there was an option to toggle the tray on the tray.

**Comment by teroparvinen** [comment]
This is a bit awkward because (unlike with the token control button) there is no way to reverse the operation and I don't want to clutter the UI with a button that may seem to work somewhat mysteriously.

I made an option that allows you to turn off the assumption that the default character is always selected, which will hide the tray when you don't have a token selected with the new option off and set to "token selected".
